pub mod bag;
pub mod cosine;
pub mod editex;
pub mod error;
pub mod identity;
pub mod jaccard;
pub mod length;
pub mod matrix;
pub mod mra;
pub mod overlap;
pub mod postfix;
pub mod prefix;
pub mod sorensen;
pub mod strcmp95;
pub mod tanimoto;
pub mod tokenizer;
pub mod traits;
pub mod tversky;
// monge_elkan module scoped out
pub mod damerau_levenshtein;

pub use bag::Bag;
pub use mra::Mra;
pub use cosine::Cosine;
pub use editex::Editex;
pub use error::TextDistanceError;
pub use identity::Identity;
pub use jaccard::Jaccard;
pub use length::Length;
pub use matrix::Matrix;
pub use overlap::Overlap;
pub use postfix::Postfix;
pub use prefix::Prefix;
pub use sorensen::Sorensen;
pub use strcmp95::StrCmp95;
pub use tanimoto::Tanimoto;
pub use tokenizer::{find_ngrams, to_char_vec, to_word_vec};
pub use traits::{DistanceMetric, SimilarityMetric};
pub use tversky::Tversky;
// MongeElkan re-export removed – scoped out
pub use damerau_levenshtein::DamerauLevenshtein;
