pub mod cosine;
pub mod error;
pub mod identity;
pub mod jaccard;
pub mod length;
pub mod matrix;
pub mod overlap;
pub mod postfix;
pub mod prefix;
pub mod sorensen;
pub mod tanimoto;
pub mod tokenizer;
pub mod traits;
pub mod tversky;

pub use cosine::Cosine;
pub use error::TextDistanceError;
pub use identity::Identity;
pub use jaccard::Jaccard;
pub use length::Length;
pub use matrix::Matrix;
pub use overlap::Overlap;
pub use postfix::Postfix;
pub use prefix::Prefix;
pub use sorensen::Sorensen;
pub use tanimoto::Tanimoto;
pub use tokenizer::{find_ngrams, to_char_vec, to_word_vec};
pub use traits::{DistanceMetric, SimilarityMetric};
pub use tversky::Tversky;
